### Particle Image Function
### Version: 1.0.4
### Width: 30
### Height: 32
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust 0.16 0 0.82 1 ^1.4333333 ^0 ^-0.3583333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^1.2541667 ^0 ^-0.5375 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^1.075 ^0 ^-0.5375 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.8958333 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.7166667 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.7166667 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.5375 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.5375 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.5375 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.3583333 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.3583333 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.3583333 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.1791667 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.1791667 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0.1791667 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0 ^0 ^-1.2541667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^0 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.1791667 ^0 ^-1.2541667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.1791667 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.1791667 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.1791667 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.3583333 ^0 ^-1.2541667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.3583333 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.3583333 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.3583333 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.5375 ^0 ^-1.2541667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.5375 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.5375 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.5375 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.5375 ^0 ^-0.5375 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.7166667 ^0 ^-1.2541667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.7166667 ^0 ^-1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.7166667 ^0 ^-0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.7166667 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.7166667 ^0 ^-0.5375 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.7166667 ^0 ^-0.3583333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.8958333 ^0 ^-0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.8958333 ^0 ^-0.5375 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.8958333 ^0 ^-0.3583333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-0.8958333 ^0 ^-0.1791667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.075 ^0 ^-0.3583333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.075 ^0 ^-0.1791667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.2541667 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.2541667 ^0 ^0.1791667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.4333333 ^0 ^0.3583333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.4333333 ^0 ^0.5375 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.4333333 ^0 ^0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.4333333 ^0 ^0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.6125 ^0 ^0.7166667 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.6125 ^0 ^0.8958333 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.6125 ^0 ^1.075 0 0 0 0 1 force @a
particle minecraft:dust 0.16 0 0.82 1 ^-1.6125 ^0 ^1.2541667 0 0 0 0 1 force @a
